### ISSUE TITLE
add Links to the readme to the titles of each rule

### ISSUE THREAD

**Issue by rowbi-wan** [netsells/eslint-config-netsells#49]
Will wait till there's fewer PRs to do this, but there should be a sub navigation on the readme to easily find the rule you want to see.

**Comment by samturrell** [comment]
Thinking it might maybe be better to split the rule descriptions into their own files to reduce merge conflicts

**Comment by samturrell** [comment]
Also potentially move rules to their own files that we can pull in dynamically using a glob. Avoid conflicts altogether that way
